name: Update Date

on:
  push:
    paths:
      - 'docs/**.md'

jobs:
  update-date:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Update Date in Modified Markdown Files
      run: |
        python .github/scripts/update_date.py