name: Update Date

on:
  push:
    paths:
      - 'docs/**.md'

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'

    - name: Update date in modified markdown files
      run: python .github/scripts/update_date.py "${{ steps.changed-files.outputs.all }}"